apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-java-spring-boot
  namespace: jenkins-demo
spec:
  output:
    to:
      kind: DockerImage
      name: quay.io/adacunha-1/hello-springboot:latest
  source:
    type: Git
    git:
      uri: https://github.com/albertina777/hello-java-spring-boot.git
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
